In [1]:
import tensorflow as tf

C:\Users\ASUS PC\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
constant = tf.constant(10)

In [3]:
fill_mat = tf.fill((4,4),10)

In [4]:
myzeros = tf.zeros((4,4))

In [5]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [6]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [7]:
my_ops = [constant, fill_mat, myzeros, myrandn, myrandu]

In [9]:
sess = tf.InteractiveSession()

In [10]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.3167273  -1.1945431   1.0360181  -0.25096527]
 [-1.7503479   0.4518899  -1.0602696  -0.24553205]
 [ 0.66493064 -0.2584674  -1.0066568   0.16221471]
 [ 1.022628   -0.4209102  -0.4428746   0.41590747]]


[[0.54099715 0.25844193 0.41861522 0.8936955 ]
 [0.08362591 0.29731143 0.543941   0.35700178]
 [0.90683556 0.6609665  0.89446557 0.501264  ]
 [0.98428977 0.79050124 0.7484311  0.15767777]]




In [11]:
a = tf.constant([[1,2],
                [3,4]])

In [12]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [13]:
b = tf.constant([[10],
                [100]])

In [14]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [15]:
result = tf.matmul(a,b)

In [16]:
sess.run(result)

array([[210],
       [430]])

In [17]:
result.eval()

array([[210],
       [430]])